version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./board_login/frontend:/var/www/html/frontend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./php
    container_name: php
    volumes:
      - ./board_login/backend:/var/www/html/backend
      - ./board_login/frontend:/var/www/html/frontend

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./create_board.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:


